######################################################################
# Automatically generated by qmake (2.00a) Mon Nov 14 20:29:32 2005
######################################################################

TEMPLATE = app
TARGET = wavemesh.bin
DEPENDPATH += . src
INCLUDEPATH += . src
QT += opengl
# Input
HEADERS += src/CfgWidgets.h src/sensor.h src/WaveSim.h src/wave_widget.h
SOURCES += src/CfgWidgets.cpp \
           src/main.cpp \
           src/sensor.cpp \
           src/WaveSim.cpp \
           src/wave_widget.cpp
